### ISSUE TITLE
Upgrade failed 4.0.1.929~ynh1,  fail to read config file

### ISSUE THREAD

**Issue by Psyquoquack** [YunoHost-Apps/sonarr_ynh#14]
### Describe the bug

Upgrade script from 3.0.6.1196~ynh3 to 4.0.1.929~ynh1 has failed due to fail of reading config file

### Context

- Hardware: Recent PC (2019) x86 amd
- YunoHost version: 11.2.10.3
- I have access to my server: Through SSH, through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: 4.0.1.929~ynh1 - master
- If upgrading, current package version: 3.0.6.1196~ynh3

### Steps to reproduce

- In CLI
    ```sh
    sudo yunohost app upgrade sonarr
    ```
- Same in web admin

### Logs

https://paste.yunohost.org/raw/ihisudayej

Love for the project!

**Comment by Billos** [comment]
Same problem here

**Comment by tituspijean** [comment]
Let me know if the new version does not fix this issue! :)

**Comment by Psyquoquack** [comment]
Thanks for the help but I got a same error. 
https://paste.yunohost.org/raw/ivalisosic

´´´
2024-04-07 11:34:29,957: INFO - [########+++++.......] > Configuring Radarr...
2024-04-07 11:34:29,957: DEBUG - + sed -i -e '$a\' /var/lib/sonarr/config.xml
2024-04-07 11:34:29,958: WARNING - sed: can't read /var/lib/sonarr/config.xml: No such file or directory
´´´
